const formatOptionLabel = (value: string): string => {
  return value
    .replace(/-/g, ' ')
    .replace(/_/g, ' ')
    .split(' ')
    .filter(Boolean)
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
};

const buildOptions = (values: string[]) =>
  values.map(value => ({
    value,
    label: formatOptionLabel(value),
  }));

export const COLOR_OPTIONS = buildOptions([
  'black',
  'white',
  'gray',
  'charcoal',
  'slate',
  'silver',
  'navy',
  'blue',
  'teal',
  'turquoise',
  'cyan',
  'sky-blue',
  'indigo',
  'green',
  'emerald',
  'mint',
  'sage',
  'forest',
  'lime',
  'olive',
  'red',
  'crimson',
  'maroon',
  'rust',
  'terracotta',
  'burgundy',
  'pink',
  'magenta',
  'fuchsia',
  'rose',
  'coral',
  'salmon',
  'purple',
  'violet',
  'eggplant',
  'lilac',
  'lavender',
  'plum',
  'yellow',
  'gold',
  'mustard',
  'amber',
  'orange',
  'peach',
  'apricot',
  'brown',
  'chocolate',
  'caramel',
  'coffee',
  'taupe',
  'tan',
  'beige',
  'cream',
  'ivory',
  'ecru',
  'camel',
  'khaki',
  'metallic',
  'multicolor',
  'other',
]);

export const FABRIC_OPTIONS = buildOptions([
  'cotton',
  'linen',
  'silk',
  'wool',
  'cashmere',
  'denim',
  'leather',
  'suede',
  'knit',
  'synthetic',
  'chiffon',
  'satin',
  'velvet',
  'lace',
  'modal',
  'rayon',
  'tencel',
  'nylon',
  'polyester',
  'cupro',
  'acetate',
  'acrylic',
  'other',
]);

export const PATTERN_OPTIONS = buildOptions([
  'solid',
  'striped',
  'plaid',
  'check',
  'floral',
  'animal',
  'polka-dot',
  'geometric',
  'graphic',
  'abstract',
  'textured',
  'other',
]);

export const SILHOUETTE_OPTIONS = buildOptions([
  'a-line',
  'column',
  'fit-and-flare',
  'cocoon',
  'trapeze',
  'bodycon',
  'wide-leg',
  'straight-leg',
  'high-rise',
  'mid-rise',
  'low-rise',
  'cropped',
  'hip-length',
  'mid-thigh',
  'waist-length',
  'knee-length',
  'long',
  'ankle-length',
  'full-length',
  'capri',
  '7/8-length',
  '3/4-length',
  'mini',
  'midi',
  'maxi',
  'tea-length',
  'floor-length',
  'long-sleeve',
  'short-sleeve',
  'sleeveless',
  'peplum',
  'asymmetrical-hem',
  'v-neck',
  'boat-neck',
  'mock-neck',
  'turtleneck',
  'crew-neck',
  'scoop-neck',
  'scoop',
  'square-neck',
  'sweetheart',
  'off-the-shoulder',
  'halter-neck',
  'cowl-neck',
  'hooded',
  'collared',
  'collarless',
  'lapel',
  'other',
]);

export const FIT_OPTIONS = buildOptions([
  'second-skin',
  'slim',
  'regular',
  'relaxed',
  'oversized',
  'tailored',
  'other',
]);

export const FORMALITY_OPTIONS = buildOptions([
  'casual',
  'smart-casual',
  'business-casual',
  'business-formal',
  'evening',
  'formal',
  'athleisure',
  'other',
]);

export const STYLE_TAG_OPTIONS = buildOptions([
  'minimalist',
  'classic',
  'modern',
  'trendy',
  'edgy',
  'boho',
  'preppy',
  'athleisure',
  'streetwear',
  'romantic',
  'feminine',
  'androgynous',
  'workwear',
  'vintage',
  'sporty',
  'heritage',
  'other',
]);

export const SEASON_OPTIONS = buildOptions([
  'spring',
  'summer',
  'fall',
  'winter',
  'all-season',
]);

export const OCCASION_OPTIONS = buildOptions([
  'work',
  'weekend',
  'date',
  'family',
  'travel',
  'party',
  'formal-event',
  'outdoor',
  'athletic',
  'lounging',
  'wedding',
  'other',
]);

export const BRAND_OPTIONS = [
  'Rick Owens',
  'Maison Margiela',
  'Ann Demeulemeester',
  'Yohji Yamamoto',
  'Comme des Garçons',
  'Issey Miyake',
  'Junya Watanabe',
  'Acne Studios',
  'Helmut Lang',
  'Raf Simons',
  'Dries Van Noten',
  'Balenciaga',
  'Vetements',
  'Dion Lee',
  'Peter Do',
  'The Row',
  'Celine',
  'Loewe',
  'Bottega Veneta',
  'Prada',
  'Miu Miu',
  'Saint Laurent',
  'Gucci',
  'Dior',
  'Chanel',
  'Versace',
  'Fendi',
  'Givenchy',
  'Jil Sander',
  'Marni',
  'Stella McCartney',
  'Vivienne Westwood',
  'Alexander McQueen',
  'Banana Republic',
  'Camper',
  'Professor E',
  'Zara',
  'H&M',
  'COS',
  'Arket',
  'Everlane',
  'Cuyana',
  'Reformation',
  'Aritzia',
  'Ganni',
  'Staud',
  'Nanushka',
  'Totême',
  'Vintage',
  'Thrift',
  'Jean Paul Gaultier',
  'Deadwood',
  'Stussy',
  'Moschino',
  'Other',
].map(value => ({
  value,
  label: value,
}));

